{ ... }:
{
  imports = [
    ./borgstor
    ./btrfsborg
    ./btrfssnapshot
    ./deployerbot
    ./frigate
    ./gitea
    ./grafana
    ./hass
    ./headscale
    ./immich
    ./jakstpub
    ./matrix-synapse
    ./minidlna
    ./node_exporter
    ./nsd-acme
    ./ping_exporter
    ./postfix
    ./printing
    ./sentinelone
    ./ssh8022
    ./syncthing
    ./syncthing-relay
    ./tailscale
    ./timelapse-r11
    ./vaultwarden
    ./wifibackup
  ];
}
