{ ... }:
{
  imports = [
    ./borgstor
    ./btrfsborg
    ./btrfssnapshot
    ./deployerbot
    ./friendlyport
    ./gitea
    ./grafana
    ./hass
    ./headscale
    ./immich
    ./jakstpub
    ./matrix-synapse
    ./minidlna
    ./node_exporter
    ./nsd-acme
    ./ping_exporter
    ./postfix
    ./printing
    ./remote-builder
    ./ssh8022
    ./syncthing
    ./syncthing-relay
    ./tailscale
    ./vaultwarden
    ./wifibackup
  ];
}
