{
  config,
  lib,
  pkgs,
  myData,
  ...
}:
let
  cfg = config.mj.services.git;

  # stagit-ng is a client-side (wasm) repo browser: the vhost serves its
  # static frontend at the root (the shipped index.html defaults derive
  # site title and clone urls from the request origin), the bare
  # repositories under *.git/ (dumb HTTP), and a repositories.txt that
  # drives the repository index page. The only per-repo server-side work
  # is `git update-server-info` plus regenerating repositories.txt on
  # pushes and repo creation.

  repolistGen = pkgs.writeShellApplication {
    name = "git-repolist-gen";
    runtimeInputs = [
      pkgs.coreutils
      pkgs.findutils
    ];
    text = ''
      tmp=$(mktemp "${cfg.repoDir}/.repositories.txt.XXXXXX")
      (cd "${cfg.repoDir}" && find . -mindepth 1 -maxdepth 2 -name '*.git' -type d | sed 's|^\./||' | sort) > "$tmp"
      chmod 644 "$tmp"
      mv "$tmp" "${cfg.repoDir}/repositories.txt"
    '';
  };

  postReceiveHook = pkgs.writeShellApplication {
    name = "post-receive";
    runtimeInputs = [
      pkgs.git
    ];
    text = ''
      # single pack per repo: keeps stagit-ng's oid lookups single-shot
      # (gc also packs refs, which keeps packed-refs current)
      git gc --quiet || true
      git update-server-info
      ${repolistGen}/bin/git-repolist-gen
    '';
  };

  newRepo = pkgs.writeShellApplication {
    name = "git-new-repo";
    runtimeInputs = with pkgs; [
      coreutils
      git
    ];
    text = ''
      if [ $# -lt 1 ] || [ $# -gt 2 ]; then
        echo "Usage: git-new-repo <org/name> [description]" >&2
        exit 1
      fi

      repopath="${cfg.repoDir}/$1.git"

      if [ ! -d "$repopath" ]; then
        mkdir -p "$(dirname "$repopath")"
        git init --bare "$repopath"
        echo "Created $repopath"
      fi

      git config -f "$repopath/config" core.sharedRepository 0644

      if [ -n "''${2:-}" ]; then
        printf '%s\n' "$2" > "$repopath/description"
      fi

      ln -sf "${cfg.repoDir}/.post-receive-hook" "$repopath/hooks/post-receive"
      git -C "$repopath" update-server-info
      ${repolistGen}/bin/git-repolist-gen
    '';
  };
in
{
  options.mj.services.git = with lib.types; {
    enable = lib.mkEnableOption "git web hosting with stagit-ng";
    repoDir = lib.mkOption { type = str; };
    sshKeys = lib.mkOption {
      type = listOf str;
      default = [ ];
    };
  };

  config = lib.mkIf cfg.enable {
    assertions = [
      {
        assertion = !config.mj.services.gitea.enable;
        message = "git and gitea cannot be enabled simultaneously (both define the git user)";
      }
    ];

    users.users.git = {
      description = "Git";
      home = cfg.repoDir;
      shell = "${pkgs.git}/bin/git-shell";
      group = "git";
      isSystemUser = true;
      createHome = true;
      homeMode = "755";
      uid = myData.uidgid.gitea;
      openssh.authorizedKeys.keys = cfg.sshKeys;
    };

    users.groups.git.gid = myData.uidgid.gitea;

    services.openssh.extraConfig = ''
      AcceptEnv GIT_PROTOCOL
    '';

    # repositories.txt is regenerated by the post-receive hook and by
    # git-new-repo. For a first deploy with pre-existing repos, seed it once
    # (alongside the one-time `git update-server-info` pass) with
    # `sudo -u git git-repolist-gen`.
    systemd.tmpfiles.rules = [
      "L+ ${cfg.repoDir}/.post-receive-hook - - - - ${postReceiveHook}/bin/post-receive"
    ];

    environment.systemPackages = [
      newRepo
      repolistGen # exposed for the one-time bootstrap above
    ];

    services.caddy.virtualHosts."git.jakstys.lt".extraConfig = ''
      header {
        Strict-Transport-Security "max-age=15768000"
        Content-Security-Policy "default-src 'none'; style-src 'self'; img-src 'self'; script-src 'self' 'wasm-unsafe-eval'; connect-src 'self'"
        X-Content-Type-Options "nosniff"
        X-Frame-Options "DENY"
        Alt-Svc "h3=\":443\"; ma=86400"
      }

      route {
        # Bare repos (dumb HTTP) and the repo list both live in repoDir.
        @repo path_regexp (\.git/|^/repositories\.txt$)
        handle @repo {
          root * ${cfg.repoDir}
          file_server
        }
        handle {
          root * ${pkgs.stagit-ng}/www
          file_server
        }
      }
    '';
  };
}
