#!/usr/bin/env python3

import argparse
from pathlib import Path


def require(source: str, fragment: str, message: str) -> None:
    assert fragment in source, message


def main() -> None:
    parser = argparse.ArgumentParser()
    parser.add_argument("--index", type=Path, required=True)
    args = parser.parse_args()
    source = args.index.read_text(encoding="utf-8")

    # The control must remain an explicit user action. Live tracking lets a
    # walker pan away while the dot continues to update in the background.
    control = source[source.index("const geolocationControl"):
                     source.index('map.on("error"')]
    require(control, "enableHighAccuracy: true", "high-accuracy positioning is disabled")
    require(control, "maximumAge: 5000", "location cache age is unbounded")
    require(control, "timeout: 12000", "location request has no sensible timeout")
    require(control, "trackUserLocation: true", "live location updates are disabled")
    require(control, "showUserLocation: true", "blue user dot is disabled")
    require(control, "showAccuracyCircle: true", "accuracy range is disabled")
    require(control, "const maxUsefulGeolocationAccuracyMeters = 10_000;",
            "implausible accuracy ranges have no UX/performance bound")
    require(control, "const maplibreGeolocationSuccess = geolocationControl._onSuccess;",
            "accuracy validation does not run before MapLibre camera/circle math")
    require(control, "_mapgamesAccuracyRejected: true",
            "rejected accuracy cannot be distinguished from a valid zero")
    require(control, "accuracy <= maxUsefulGeolocationAccuracyMeters",
            "large finite accuracy reaches MapLibre unchanged")
    require(control, 'map.addControl(geolocationControl, "top-left")',
            "geolocation control is not installed")
    assert ".trigger()" not in control, "location permission is requested without a button press"

    # No event handler may serialize or log the device coordinates. Camera
    # move events generated by the control and the whole active-watch period
    # are excluded from view hashes.
    require(source, "if (geolocationPrivacyActive || geolocationCameraTainted) return;",
            "device-derived camera can schedule a view hash")
    require(source, "geolocationPrivacyActive || geolocationCameraTainted || !metadata",
            "device-derived camera can be serialized after tracking stops")
    require(source, "geolocationCameraTainted = true;",
            "successful device fixes do not permanently taint the session camera")
    require(source, "if (!event.geolocateSource) scheduleViewHash();",
            "device-follow camera changes can update the URL")
    require(source, "clearTimeout(viewHashTimer);",
            "a hash write queued before geolocation is not cancelled")
    require(source, "geolocationPrivacyActive = true;",
            "geolocation does not engage the privacy guard")
    handlers = source[source.index('geolocationControl.on("trackuserlocationstart"'):
                      source.index('const geolocationCapable')]
    for forbidden in ("writeHash(", "updateInspectionHash(", "inspectLocation(",
                      "console.", "fetch(", "XMLHttpRequest", "sendBeacon"):
        assert forbidden not in handlers, f"geolocation handler leaks or inspects location via {forbidden}"
    require(source,
            '".maplibregl-user-location-dot, .maplibregl-user-location-accuracy-circle"',
            "location marker clicks are not isolated from map inspection")

    # The status region and every terminal API outcome are bilingual. The
    # status carries accuracy only, never latitude/longitude.
    require(source, 'id="geolocation-status"', "geolocation has no visible status region")
    require(source, 'role="status"', "geolocation status is not announced")
    require(source, 'aria-live="polite"', "geolocation status is not an aria live region")
    for key in (
        "geolocationStopButton", "geolocationRecenterButton", "geolocationUnavailableButton",
        "geolocationLocating", "geolocationTracking",
        "geolocationBackground", "geolocationOff", "geolocationDenied",
        "geolocationUnavailable", "geolocationPositionUnavailable",
        "geolocationTimeout", "geolocationOutside",
    ):
        assert source.count(f"{key}:") == 2, f"missing bilingual geolocation string: {key}"
    require(source, "renderGeolocationStatus();",
            "language changes do not translate the current location state")
    require(source, 'setTimeout(() => { status.hidden = true; }, 6000)',
            "successful geolocation status permanently clutters the map")
    require(source, 'geolocationCameraFollowing ? "geolocationStopButton" : "geolocationRecenterButton"',
            "active geolocation button does not expose its next action")

    # Unsupported and insecure contexts stay disabled even after MapLibre's
    # asynchronous support check. Reduced-motion and coarse/mobile UI remain
    # first-class rather than browser-default accidents.
    require(source, 'typeof navigator.geolocation?.watchPosition === "function"',
            "insecure or unsupported contexts are not handled")
    require(source, 'new MutationObserver(() => {',
            "async MapLibre support resolution is not observed")
    require(source, 'if (!geolocationCapable && !geolocationButton.disabled) {',
            "unsupported-context observer can recursively rewrite disabled state")
    require(source, 'attributeFilter: ["disabled"]',
            "disabled-state localization is not maintained")
    require(source, 'reducedMotionMedia.matches ? 0 : 450',
            "camera movement ignores reduced-motion preferences")
    require(source, ".maplibregl-user-location-accuracy-circle {",
            "accuracy circle has no deliberate visual treatment")
    require(source, "accuracyCircle.hidden = !(lastGeolocationAccuracy > 0);",
            "rejected accuracy leaves a misleading circle visible")
    require(source, ".maplibregl-ctrl-group button,",
            "mobile controls have no 44px touch-target rule")

    print("geolocation UI contract passed")


if __name__ == "__main__":
    main()
