{
  lib,
  stdenvNoCC,
  fetchgit,
  fetchurl,
  compressDrvWeb,
  runCommand,
  # mitchellh's zig-overlay (flake input `zig`, its overlay applied in
  # flake.nix), which exposes upstream's released zig binaries as
  # `zigpkgs.<version>`. maps.jakstys.lt pins
  # `minimum_zig_version = "0.16.0"`, and stable nixpkgs 26.05 only ships zig
  # <= 0.13, so the alternative would be nixpkgs-unstable's zig_0_16 -- but
  # unstable churns constantly and every churn rebuilds this entire pipeline,
  # whereas the overlay's pin only moves when upstream cuts a new release.
  zigpkgs,
  # Optional local lt-shelters snapshot (a directory with priedangos.jsonl,
  # kas.jsonl, refreshed-at.txt and LICENSE-DATA.md). As of maps Phase 3
  # (design §C.4 / decision 4) the snapshot left build.zig.zon: build.zig no
  # longer fetches it and REQUIRES `-Dshelters=<dir>` for every data step. null
  # therefore means "use the pinned sha256-object lt-shelters.git HEAD fetched
  # by config below" (the normal production path). Override with a checkout for
  # shelter-data iteration.
  sheltersSrc ? null,
  # Production default: the pinned sha256-object maps.jakstys.lt HEAD.
  # Override with the cleanSourceWith local-checkout expression below for
  # iteration (kept here commented for copy-paste):
  #   lib.cleanSourceWith { src = ../../../../maps.jakstys.lt; filter = path: type:
  #     let name = baseNameOf path; in
  #     !(name == ".git" || name == ".zig-cache" || name == "zig-out" || name == "zig-pkg"); }
  mapsRev ? "a0da4de41d3a43cf08ebe6da27cd67a94aa52fc69a4e12c0f4e59511212bcda8",
  mapsSrc ? null,
  # null means "use up to 8 $NIX_BUILD_CORES at build time" for generation workers.
  concurrency ? null,
  expansionConcurrencyCap ? 8,
  expansionBatchSize ? 128,
  # Full Lithuania PBF extent. Build time and peak memory are measured per
  # phase by the native mapmaker programs.
  bbox ? "20.618591,53.892206,26.83873,56.45329",
  # bbox ? "24.95,54.52,25.55,54.92", # Vilnius prototype/iteration area
}:

assert lib.assertMsg (
  concurrency == null || (builtins.isInt concurrency && concurrency > 0)
) "mapgames: concurrency must be a positive integer";
assert lib.assertMsg (
  builtins.isInt expansionConcurrencyCap && expansionConcurrencyCap > 0
) "mapgames: expansionConcurrencyCap must be a positive integer";
assert lib.assertMsg (
  builtins.isInt expansionBatchSize && expansionBatchSize > 0
) "mapgames: expansionBatchSize must be a positive integer";

let
  version = "260716";

  # The maps source: pinned fetchgit by default (rev+hash computed off-daemon
  # per AGENTS.md §8.1, method validated against the prior pin), local
  # checkout when the mapsSrc arg is supplied for iteration.
  maps =
    if mapsSrc != null then
      mapsSrc
    else
      fetchgit {
        url = "https://git.jakstys.lt/maps.jakstys.lt.git";
        rev = mapsRev;
        preFetch = "export GIT_DEFAULT_HASH=sha256"; # repo is sha256 object format
        hash = "sha256-ALGps1/6yztKJQztuYtCP6e6/WUjSPX+nl5FvlHsaKo=";
      };

  # Zig 0.16.0 from zig-overlay (upstream's release tarball), used for
  # dependency fetching and every build. NOTE: unlike nixpkgs' zig this
  # derivation carries NO setup-hook, so nothing sets ZIG_GLOBAL_CACHE_DIR or
  # substitutes build/install phases for us; every derivation below therefore
  # exports the cache dir itself (see zigCommon / zigDeps). The fetched
  # dependency set (zigDeps) is unaffected by the switch: package hashes are
  # content-addressed and both toolchains are 0.16.0, verified off-daemon by
  # replicating the FOD builder with this exact binary (same NAR hash).
  zig = zigpkgs."0.16.0";

  # Never let Zig infer the target from the build host. Nix's platform names
  # are mapped explicitly to the spellings accepted by maps' -Dtarget option.
  zigTargets = {
    "x86_64-linux" = "x86_64-linux-musl";
    "aarch64-linux" = "aarch64-linux-musl";
    "aarch64-darwin" = "aarch64-macos";
  };
  zigTarget =
    zigTargets.${stdenvNoCC.hostPlatform.system}
      or (throw "mapgames: unsupported platform ${stdenvNoCC.hostPlatform.system}");
  targetFlag = "-Dtarget=${zigTarget}";

  # maps.jakstys.lt is a static site generated by Zig. The package is split so
  # deps and CODE live in their own derivations and a data-input bump (pbf /
  # shelters snapshot) rebuilds only the data/site derivations:
  #   1. zigDeps   -- build.zig.zon dependency FOD          (src + network)
  #   2. mapmaker  -- every compiled pipeline program        (src + zigDeps)
  #   3. site/data -- generation only, consumes the prebuilt programs via
  #                   -Dmapmaker=${mapmaker}                 (+ pbf, shelters)
  # site/data still link zigDeps (build.zig has no lazy deps, and the cheap
  # host-side site tools compile in-graph), but none of the heavy native code
  # (valhalla/tilemaker/luajit/mapmaker) recompiles when only data changes.

  # ── Deriv 1: zigDeps ──────────────────────────────────────────────────────
  # All build.zig.zon dependencies of the *root* package (native source
  # tarballs incl. Boost/SQLite/Valhalla/Tilemaker/osmium and the browser-asset
  # archives) as one fixed-output derivation. As of maps Phase 3 the Lithuania
  # PBF and lt-shelters snapshot are NO LONGER manifest deps (they left
  # build.zig.zon, design §C.4); config fetches them separately (pbfSrc /
  # shelters below) and passes them as -Dpbf/-Dshelters.
  #
  # Hand-rolled: it started as nixpkgs' `zig.fetchDeps`
  # (pkgs/development/compilers/zig/fetcher.nix) inlined with ONE fix,
  # `mkdir -p "$ZIG_GLOBAL_CACHE_DIR/tmp"` -- Zig 0.16 writes the temp download
  # for a `.zip` dependency under $ZIG_GLOBAL_CACHE_DIR/tmp but does not create
  # that dir, and fetcher.nix `mktemp -d`s the cache without it, so plain
  # `zig.fetchDeps` failed on the sqlite `.zip` amalgamation with
  # `error: failed to create temporary zip file: FileNotFound` (confirmed on a
  # real `nix build`; `.tar.gz` deps are unaffected). Now that zig comes from
  # zig-overlay (no fetchDeps helper, no setup-hook) this is simply THE builder,
  # not a workaround copy.
  #
  # `--fetch=all` (not `--fetch`) is REQUIRED: the Nix build phase has no network
  # -- only this FOD does -- so every dep Zig resolves at build time, including
  # any LAZY ones, must already be in the pre-fetched `p/`.
  #
  # `outputHash` is the NAR of the fetched `p/`. The method was validated by
  # reproducing the previous hash
  # sha256-coWBU6PpXmiIqFY0En4pZxbwdQwOUwd25QwLiUdVcW8= from the old pinned tree,
  # then re-run against the staged static-site dependency set. The
  # nixpkgs-unstable -> zig-overlay compiler switch does NOT move it: replaying
  # this builder off-daemon with the overlay's 0.16.0 binary
  # (ziglang.org/download/0.16.0/zig-x86_64-linux-0.16.0.tar.xz, sha256
  # 70e49664...3d00 as pinned in the overlay's sources.json) against maps
  # 1603e63b reproduced the hash below byte-for-byte (75 packages).
  zigDeps =
    runCommand "mapgames-${version}-zig-deps"
      {
        src = maps;
        nativeBuildInputs = [ zig ];
        outputHashAlgo = null;
        outputHashMode = "recursive";
        outputHash = "sha256-YE89PdbXTLRWDAnPzRWsRu0La1b5Jv+oBoNSI/+j234="; # zig-deps NAR (maps 61cccfc4: GEOS/proj/bzip2/host-sqlite packages dropped from build.zig.zon)
      }
      ''
        export ZIG_GLOBAL_CACHE_DIR=$(mktemp -d)
        mkdir -p "$ZIG_GLOBAL_CACHE_DIR/tmp" # sqlite .zip temp dir (see comment above)
        runHook unpackPhase
        cd "$sourceRoot"
        zig build --fetch=all ${targetFlag}
        mv "$ZIG_GLOBAL_CACHE_DIR/p" "$out"
      '';

  # Point Zig's global cache at a writable build-local dir and expose the
  # pre-fetched dependency set as that cache's package store, so `zig build`
  # never touches the network. zig-overlay's zig has no setup-hook (nixpkgs'
  # zigConfigurePhase used to export ZIG_GLOBAL_CACHE_DIR), so the export is
  # done here; it is run from postConfigure and, since all phases share one
  # shell, stays in effect for buildPhase. The sandbox has no writable $HOME,
  # but nothing consults it once the global cache is set explicitly, and Zig's
  # local cache defaults to ./.zig-cache in the (writable) build dir.
  setupZigCache = ''
    export ZIG_GLOBAL_CACHE_DIR="$NIX_BUILD_TOP/zig-global-cache"
    mkdir -p "$ZIG_GLOBAL_CACHE_DIR"
    ln -s ${zigDeps} "$ZIG_GLOBAL_CACHE_DIR/p"
  '';

  # build.zig no longer fetches data inputs; config supplies them as
  # -Dpbf/-Dshelters on every data/site build.
  #
  # pbfSrc: the raw Lithuania .osm.pbf via fetchurl (flat file, plain download --
  # not a tarball; build.zig takes the bare .pbf path). Unchanged across the
  # 403a9ea6 -> 419692f bump (same lithuania-260716 snapshot).
  pbfSrc = fetchurl {
    url = "https://dl.jakstys.lt/maps/lithuania-260716.osm.pbf";
    hash = "sha256-7X/oYyrVG9nVF8Qeqkof1OvPUi7KrNEjnxvqkZgG5fw=";
  };

  # shelters: the lt-shelters snapshot dir. Production default = the pinned
  # sha256-object lt-shelters.git HEAD via fetchgit (verified to exist as a real
  # sha256 repo; git.jakstys.lt is sha256 object format, so preFetch sets
  # GIT_DEFAULT_HASH -- same proven pattern as mapsSrc). Override sheltersSrc with
  # a local checkout for shelter-data iteration. Bump sheltersRev + hash together.
  sheltersRev = "1131eb85efe466ca01a30bf6e761a09f5a8da9d42c28e1087540b0e0bb6f657e";
  shelters =
    if sheltersSrc != null then
      sheltersSrc
    else
      fetchgit {
        url = "https://git.jakstys.lt/lt-shelters.git";
        rev = sheltersRev;
        preFetch = "export GIT_DEFAULT_HASH=sha256"; # repo is sha256 object format
        hash = "sha256-UDz6jmf/KJvlzqKHZ5uAJHPazxP2GzZJRJVk+tQHLB4=";
      };

  # Generation-tuning flags shared by every data `zig build` invocation.
  genFlagList = [
    "-Dbbox=${bbox}"
    "-Dexpansion-concurrency-cap=${toString expansionConcurrencyCap}"
    "-Dexpansion-batch-size=${toString expansionBatchSize}"
  ];

  # The REQUIRED data inputs, added ONLY to data-building targets (site, data).
  dataInputFlags = [
    "-Dpbf=${pbfSrc}"
    "-Dshelters=${shelters}"
  ];
  dataFlagsEscaped = lib.escapeShellArgs (genFlagList ++ dataInputFlags);

  # concurrency is resolved in-shell so it can honor $NIX_BUILD_CORES when unset.
  resolveConcurrency =
    if concurrency == null then
      ''
        mapgames_concurrency="$NIX_BUILD_CORES"
        if [ "$mapgames_concurrency" -gt 8 ]; then
          mapgames_concurrency=8
        fi
      ''
    else
      "mapgames_concurrency=${toString concurrency}";

  # Shared skeleton for the explicit-target zig derivations: set up the global
  # cache + pre-fetched deps in postConfigure. Every derivation below spells
  # out its own buildPhase/installPhase, so maps' own optimize/cpu selection is
  # what runs (the no-option build is ReleaseFast; build.zig owns the audit) --
  # there is no setup-hook injecting default flags or phases.
  zigCommon = {
    inherit version;
    src = maps;
    postConfigure = setupZigCache;
  };

  meta = {
    homepage = "https://maps.jakstys.lt/";
    license = with lib.licenses; [
      mit
      odbl
      bsd2
      bsd3
      ofl
    ];
    platforms = [
      "x86_64-linux"
      "aarch64-linux"
      "aarch64-darwin"
    ];
  };

  # ── Deriv 2: mapmaker (CODE) ──────────────────────────────────────────────
  # `zig build mapmaker` compiles and installs the complete pipeline-program
  # roster (build.zig MapmakerExes: 11 mapmaker-* binaries plus their native
  # deps -- valhalla, tilemaker, luajit, sqlite...). Depends on mapsSrc +
  # zigDeps ONLY -- no pbf/shelters -- so data-snapshot bumps reuse it from
  # cache. build.zig validates the tree at configure time (regular, non-empty,
  # executable) when site/data consume it via -Dmapmaker.
  mapmaker = stdenvNoCC.mkDerivation (
    zigCommon
    // {
      pname = "mapgames-mapmaker";
      nativeBuildInputs = [ zig ];
      enableParallelBuilding = true;
      buildPhase = ''
        runHook preBuild
        zig build mapmaker ${targetFlag}
        runHook postBuild
      '';
      installPhase = ''
        runHook preInstall
        cp -r zig-out "$out"
        runHook postInstall
      '';
      meta = meta // {
        description = "Compiled maps.jakstys.lt pipeline programs (bin/mapmaker-*), data-input independent";
      };
    }
  );

  # ── Deriv 3: site + data (generation only) ────────────────────────────────
  # `zig build site` generates the country data and assembles the deployable
  # zig-out/www. It takes the two external data inputs as -Dpbf/-Dshelters and
  # runs the prebuilt pipeline programs from the mapmaker derivation.
  site = stdenvNoCC.mkDerivation (
    zigCommon
    // {
      pname = "mapgames-site";
      nativeBuildInputs = [ zig ];
      # Full-country generation is single-derivation heavy work; give it the
      # whole sandbox and do not let Zig fan out beyond the requested workers.
      enableParallelBuilding = true;
      buildPhase = ''
        runHook preBuild
        ${resolveConcurrency}
        zig build site ${targetFlag} ${dataFlagsEscaped} \
          -Dmapmaker=${mapmaker} \
          -Dconcurrency="$mapgames_concurrency"
        runHook postBuild
      '';
      installPhase = ''
        runHook preInstall
        cp -r zig-out/www "$out"
        runHook postInstall
      '';
      meta = meta // {
        description = "Deployable maps.jakstys.lt site (zig-out/www) for a configured Lithuania snapshot region";
      };
    }
  );

  # ── Deriv 4: compressed (DEPLOYER-SIDE sidecars) ──────────────────────────
  # nixpkgs' web compressor adds zstd/brotli/zopfli siblings for the usual web
  # formats. Add maps' search index, glyph ranges, and wasm engine explicitly;
  # PMTiles remain outside the format list and are served identity-only with
  # Range requests.
  compressed = compressDrvWeb site {
    extraFormats = [
      "bin"
      "pbf"
      "wasm"
    ];
  };

  # On-demand `zig build data` (zig-out/data): the generated JSON + PMTiles,
  # validated by the data-check gate. Exposed through passthru so the raw data
  # can be built/inspected without the browser-asset assembly.
  data = stdenvNoCC.mkDerivation (
    zigCommon
    // {
      pname = "mapgames-data";
      nativeBuildInputs = [ zig ];
      buildPhase = ''
        runHook preBuild
        ${resolveConcurrency}
        zig build data ${targetFlag} ${dataFlagsEscaped} \
          -Dmapmaker=${mapmaker} \
          -Dconcurrency="$mapgames_concurrency"
        runHook postBuild
      '';
      installPhase = ''
        runHook preInstall
        cp -r zig-out/data "$out"
        runHook postInstall
      '';
      meta = meta // {
        description = "Generated JSON and PMTiles (zig-out/data) for a configured Lithuania snapshot region";
      };
    }
  );
in
# The deployable artifact is zig-out/www: a content-addressed object graph
# (hash-named objects and web-graph.json, all produced by the Zig site build
# tools). Compression is the deployer's job.
# Production Caddy imports mapsSrc/deploy/Caddyfile.snippet and serves this store
# path directly. passthru is metadata only, so this override yields the SAME
# store path as `site` (no second heavy build).
site.overrideAttrs (_: {
  passthru = {
    mapsSrc = maps;
    inherit
      zigDeps
      mapmaker
      site
      data
      compressed
      ;
  };
})
