{
  lib,
  stdenvNoCC,
  fetchgit,
  fetchurl,
  runCommand,
  # nixpkgs-unstable package set (exposed by the flake overlay). Stable
  # nixpkgs 26.05 only ships zig <= 0.13; maps.jakstys.lt requires zig 0.16 and
  # the zig `fetchDeps` fixed-output-derivation helper, both of which live in
  # unstable (zig.default == zig_0_16 == 0.16.0).
  pkgs-unstable,
  # Optional local lt-shelters snapshot (a directory with priedangos.jsonl,
  # kas.jsonl, refreshed-at.txt and LICENSE-DATA.md). As of maps Phase 3
  # (design §C.4 / decision 4) the snapshot left build.zig.zon: build.zig no
  # longer fetches it and REQUIRES `-Dshelters=<dir>` for every data step. null
  # therefore means "use the pinned sha256-object lt-shelters.git HEAD fetched
  # by config below" (the normal production path). Override with a checkout for
  # shelter-data iteration.
  sheltersSrc ? null,
  # Production default: the pinned sha256-object maps.jakstys.lt HEAD.
  # Override with the cleanSourceWith local-checkout expression below for
  # iteration (kept here commented for copy-paste):
  #   lib.cleanSourceWith { src = ../../../../maps.jakstys.lt; filter = path: type:
  #     let name = baseNameOf path; in
  #     !(name == ".git" || name == ".zig-cache" || name == "zig-out" || name == "zig-pkg"); }
  mapsRev ? "50dfba72c49342ed51583378b74dda46ba7e4be8fb21e698514001df153d1319",
  mapsSrc ? null,
  # null means "use up to 8 $NIX_BUILD_CORES at build time" for generation workers.
  concurrency ? null,
  expansionConcurrencyCap ? 8,
  expansionBatchSize ? 128,
  # Full Lithuania PBF extent. Build time and peak memory are measured per
  # phase by the native mapmaker programs.
  bbox ? "20.618591,53.892206,26.83873,56.45329",
  # bbox ? "24.95,54.52,25.55,54.92", # Vilnius prototype/iteration area
}:

assert lib.assertMsg (
  concurrency == null || (builtins.isInt concurrency && concurrency > 0)
) "mapgames: concurrency must be a positive integer";
assert lib.assertMsg (
  builtins.isInt expansionConcurrencyCap && expansionConcurrencyCap > 0
) "mapgames: expansionConcurrencyCap must be a positive integer";
assert lib.assertMsg (
  builtins.isInt expansionBatchSize && expansionBatchSize > 0
) "mapgames: expansionBatchSize must be a positive integer";

let
  version = "260716";

  # The maps source: pinned fetchgit by default (rev+hash computed off-daemon
  # per AGENTS.md §8.1, method validated against the prior pin), local
  # checkout when the mapsSrc arg is supplied for iteration.
  maps =
    if mapsSrc != null then
      mapsSrc
    else
      fetchgit {
        url = "https://git.jakstys.lt/maps.jakstys.lt.git";
        rev = mapsRev;
        preFetch = "export GIT_DEFAULT_HASH=sha256"; # repo is sha256 object format
        hash = "sha256-Unr3w7GpQLZYk57Uatcnblp3KyaBlo4rjp9iHYaTCvc=";
      };

  # Zig 0.16 from nixpkgs-unstable, used for dependency fetching and every
  # build. maps.jakstys.lt pins `minimum_zig_version = "0.16.0"`.
  zig = pkgs-unstable.zig_0_16;

  # maps.jakstys.lt is a static site generated by Zig. The package is split so
  # deps and CODE live in their own derivations and a data-input bump (pbf /
  # shelters snapshot) rebuilds only the data/site derivations:
  #   1. zigDeps   -- build.zig.zon dependency FOD          (src + network)
  #   2. mapmaker  -- every compiled pipeline program        (src + zigDeps)
  #   3. site/data -- generation only, consumes the prebuilt programs via
  #                   -Dmapmaker=${mapmaker}                 (+ pbf, shelters)
  # site/data still link zigDeps (build.zig has no lazy deps, and the cheap
  # host-side site tools compile in-graph), but none of the heavy native code
  # (valhalla/tilemaker/luajit/mapmaker) recompiles when only data changes.

  # ── Deriv 1: zigDeps ──────────────────────────────────────────────────────
  # All build.zig.zon dependencies of the *root* package (native source
  # tarballs incl. Boost/SQLite/Valhalla/Tilemaker/osmium and the browser-asset
  # archives) as one fixed-output derivation. As of maps Phase 3 the Lithuania
  # PBF and lt-shelters snapshot are NO LONGER manifest deps (they left
  # build.zig.zon, design §C.4); config fetches them separately (pbfSrc /
  # shelters below) and passes them as -Dpbf/-Dshelters.
  #
  # This is nixpkgs' `zig.fetchDeps` (pkgs/development/compilers/zig/fetcher.nix)
  # inlined with ONE fix: `mkdir -p "$ZIG_GLOBAL_CACHE_DIR/tmp"`. Zig 0.16 writes
  # the temp download for a `.zip` dependency under $ZIG_GLOBAL_CACHE_DIR/tmp but
  # does not create that dir, and fetcher.nix `mktemp -d`s the cache without it,
  # so plain `zig.fetchDeps` fails on the sqlite `.zip` amalgamation with
  # `error: failed to create temporary zip file: FileNotFound` (confirmed on a
  # real `nix build`; `.tar.gz` deps are unaffected). TODO: drop this inline copy
  # for plain `zig.fetchDeps` once nixpkgs' fetcher.nix creates tmp/ (worth
  # upstreaming).
  #
  # `--fetch=all` (not `--fetch`) is REQUIRED: the Nix build phase has no network
  # -- only this FOD does -- so every dep Zig resolves at build time, including
  # any LAZY ones, must already be in the pre-fetched `p/`.
  #
  # `outputHash` is the NAR of the fetched `p/`. The method was validated by
  # reproducing the previous hash
  # sha256-coWBU6PpXmiIqFY0En4pZxbwdQwOUwd25QwLiUdVcW8= from the old pinned tree,
  # then re-run against the staged static-site dependency set.
  zigDeps =
    runCommand "mapgames-${version}-zig-deps"
      {
        src = maps;
        nativeBuildInputs = [ zig ];
        outputHashAlgo = null;
        outputHashMode = "recursive";
        outputHash = "sha256-YE89PdbXTLRWDAnPzRWsRu0La1b5Jv+oBoNSI/+j234="; # zig-deps NAR (maps 61cccfc4: GEOS/proj/bzip2/host-sqlite packages dropped from build.zig.zon)
      }
      ''
        export ZIG_GLOBAL_CACHE_DIR=$(mktemp -d)
        mkdir -p "$ZIG_GLOBAL_CACHE_DIR/tmp" # sqlite .zip temp dir (see comment above)
        runHook unpackPhase
        cd "$sourceRoot"
        zig build --fetch=all
        mv "$ZIG_GLOBAL_CACHE_DIR/p" "$out"
      '';

  # The pre-fetched dependency set, exposed as the global cache's package store
  # so `zig build` never touches the network. The nixpkgs zig setup-hook's
  # zigConfigurePhase sets ZIG_GLOBAL_CACHE_DIR=$(mktemp -d); this link is done
  # from postConfigure, which runs *after* that (NOT postPatch, where the cache
  # dir is not set yet). The sandbox has no writable $HOME, but the hook points
  # the global cache at a writable temp dir and Zig's local cache defaults to
  # ./.zig-cache in the (writable) build dir, so no manual HOME / cache-dir
  # exports are needed.
  linkZigDeps = ''ln -s ${zigDeps} "$ZIG_GLOBAL_CACHE_DIR/p"'';

  # build.zig no longer fetches data inputs; config supplies them as
  # -Dpbf/-Dshelters on every data/site build.
  #
  # pbfSrc: the raw Lithuania .osm.pbf via fetchurl (flat file, plain download --
  # not a tarball; build.zig takes the bare .pbf path). Unchanged across the
  # 403a9ea6 -> 419692f bump (same lithuania-260716 snapshot).
  pbfSrc = fetchurl {
    url = "https://dl.jakstys.lt/maps/lithuania-260716.osm.pbf";
    hash = "sha256-7X/oYyrVG9nVF8Qeqkof1OvPUi7KrNEjnxvqkZgG5fw=";
  };

  # shelters: the lt-shelters snapshot dir. Production default = the pinned
  # sha256-object lt-shelters.git HEAD via fetchgit (verified to exist as a real
  # sha256 repo; git.jakstys.lt is sha256 object format, so preFetch sets
  # GIT_DEFAULT_HASH -- same proven pattern as mapsSrc). Override sheltersSrc with
  # a local checkout for shelter-data iteration. Bump sheltersRev + hash together.
  sheltersRev = "1131eb85efe466ca01a30bf6e761a09f5a8da9d42c28e1087540b0e0bb6f657e";
  shelters =
    if sheltersSrc != null then
      sheltersSrc
    else
      fetchgit {
        url = "https://git.jakstys.lt/lt-shelters.git";
        rev = sheltersRev;
        preFetch = "export GIT_DEFAULT_HASH=sha256"; # repo is sha256 object format
        hash = "sha256-UDz6jmf/KJvlzqKHZ5uAJHPazxP2GzZJRJVk+tQHLB4=";
      };

  # Generation-tuning flags shared by every data `zig build` invocation.
  genFlagList = [
    "-Dbbox=${bbox}"
    "-Dexpansion-concurrency-cap=${toString expansionConcurrencyCap}"
    "-Dexpansion-batch-size=${toString expansionBatchSize}"
  ];

  # The REQUIRED data inputs, added ONLY to data-building targets (site, data).
  dataInputFlags = [
    "-Dpbf=${pbfSrc}"
    "-Dshelters=${shelters}"
  ];
  dataFlagsEscaped = lib.escapeShellArgs (genFlagList ++ dataInputFlags);

  # concurrency is resolved in-shell so it can honor $NIX_BUILD_CORES when unset.
  resolveConcurrency =
    if concurrency == null then
      ''
        mapgames_concurrency="$NIX_BUILD_CORES"
        if [ "$mapgames_concurrency" -gt 8 ]; then
          mapgames_concurrency=8
        fi
      ''
    else
      "mapgames_concurrency=${toString concurrency}";

  # Shared skeleton for the explicit-target zig derivations. The nixpkgs zig setup-hook still runs its
  # zigConfigurePhase (ZIG_GLOBAL_CACHE_DIR) and we link the pre-fetched deps in
  # postConfigure; dontSetZigDefaultFlags keeps maps' own optimize/cpu selection
  # (the no-option build is ReleaseFast; build.zig owns the audit).
  zigCommon = {
    inherit version;
    src = maps;
    dontSetZigDefaultFlags = true;
    postConfigure = linkZigDeps;
    dontUseZigBuild = true;
    dontUseZigInstall = true;
  };

  meta = {
    homepage = "https://maps.jakstys.lt/";
    license = with lib.licenses; [
      mit
      odbl
      bsd2
      bsd3
      ofl
    ];
    platforms = [ "x86_64-linux" ];
  };

  # ── Deriv 2: mapmaker (CODE) ──────────────────────────────────────────────
  # `zig build mapmaker` compiles and installs the complete pipeline-program
  # roster (build.zig MapmakerExes: 11 mapmaker-* binaries plus their native
  # deps -- valhalla, tilemaker, luajit, sqlite...). Depends on mapsSrc +
  # zigDeps ONLY -- no pbf/shelters -- so data-snapshot bumps reuse it from
  # cache. build.zig validates the tree at configure time (regular, non-empty,
  # executable) when site/data consume it via -Dmapmaker.
  mapmaker = stdenvNoCC.mkDerivation (
    zigCommon
    // {
      pname = "mapgames-mapmaker";
      nativeBuildInputs = [ zig ];
      enableParallelBuilding = true;
      buildPhase = ''
        runHook preBuild
        zig build mapmaker
        runHook postBuild
      '';
      installPhase = ''
        runHook preInstall
        cp -r zig-out "$out"
        runHook postInstall
      '';
      meta = meta // {
        description = "Compiled maps.jakstys.lt pipeline programs (bin/mapmaker-*), data-input independent";
      };
    }
  );

  # ── Deriv 3: site + data (generation only) ────────────────────────────────
  # `zig build site` generates the country data and assembles the deployable
  # zig-out/www. It takes the two external data inputs as -Dpbf/-Dshelters and
  # runs the prebuilt pipeline programs from the mapmaker derivation.
  site = stdenvNoCC.mkDerivation (
    zigCommon
    // {
      pname = "mapgames-site";
      nativeBuildInputs = [ zig ];
      # Full-country generation is single-derivation heavy work; give it the
      # whole sandbox and do not let Zig fan out beyond the requested workers.
      enableParallelBuilding = true;
      buildPhase = ''
        runHook preBuild
        ${resolveConcurrency}
        zig build site ${dataFlagsEscaped} \
          -Dmapmaker=${mapmaker} \
          -Dconcurrency="$mapgames_concurrency"
        runHook postBuild
      '';
      installPhase = ''
        runHook preInstall
        cp -r zig-out/www "$out"
        runHook postInstall
      '';
      meta = meta // {
        description = "Deployable maps.jakstys.lt site (zig-out/www) for a configured Lithuania snapshot region";
      };
    }
  );

  # ── Deriv 4: compressed (DEPLOYER-SIDE sidecars) ──────────────────────────
  # Owner policy: all assets are served with precompressed sidecars in three
  # codecs — zstd -19 (.zst), brotli max (.br), zopfli (.gz, best-possible
  # gzip) — negotiated by Caddy's `precompressed` directive via Accept-Encoding.
  # The maps BUILD stays raw (compression is the deployer's job — this
  # derivation IS the deployer layer); the site derivation is symlinked and
  # sidecars are added next to every file. Exclusions:
  #   *.pmtiles — served identity-only with Range requests (the Caddy snippet
  #   pins them to @identityOnly); a sidecar would never be used.
  # A sidecar that fails to beat the original (already-compressed payloads,
  # e.g. PNG) is dropped so Caddy falls back to identity or on-the-fly encode.
  compressed =
    runCommand "mapgames-${version}-www-compressed"
      {
        nativeBuildInputs = with pkgs-unstable; [
          zstd
          brotli
          zopfli
        ];
      }
      ''
        mkdir -p "$out"
        (cd ${site} && find . -type d) | while read -r d; do mkdir -p "$out/$d"; done
        (cd ${site} && find . -type f) | while read -r f; do
          src=${site}/"$f"
          ln -s "$src" "$out/$f"
          case "$f" in
            *.pmtiles) continue ;;
          esac
          size=$(stat -Lc %s "$src")
          zstd -19 -q -c "$src" > "$out/$f.zst"
          [ "$(stat -c %s "$out/$f.zst")" -lt "$size" ] || rm "$out/$f.zst"
          brotli -q 11 -c "$src" > "$out/$f.br"
          [ "$(stat -c %s "$out/$f.br")" -lt "$size" ] || rm "$out/$f.br"
          zopfli -c "$src" > "$out/$f.gz"
          [ "$(stat -c %s "$out/$f.gz")" -lt "$size" ] || rm "$out/$f.gz"
        done
      '';

  # On-demand `zig build data` (zig-out/data): the generated JSON + PMTiles,
  # validated by the data-check gate. Exposed through passthru so the raw data
  # can be built/inspected without the browser-asset assembly.
  data = stdenvNoCC.mkDerivation (
    zigCommon
    // {
      pname = "mapgames-data";
      nativeBuildInputs = [ zig ];
      buildPhase = ''
        runHook preBuild
        ${resolveConcurrency}
        zig build data ${dataFlagsEscaped} \
          -Dmapmaker=${mapmaker} \
          -Dconcurrency="$mapgames_concurrency"
        runHook postBuild
      '';
      installPhase = ''
        runHook preInstall
        cp -r zig-out/data "$out"
        runHook postInstall
      '';
      meta = meta // {
        description = "Generated JSON and PMTiles (zig-out/data) for a configured Lithuania snapshot region";
      };
    }
  );
in
# The deployable artifact is zig-out/www: a content-addressed object graph
# (hash-named objects and web-graph.json, all produced by the Zig site build
# tools). Compression is the deployer's job.
# Production Caddy imports mapsSrc/deploy/Caddyfile.snippet and serves this store
# path directly. passthru is metadata only, so this override yields the SAME
# store path as `site` (no second heavy build).
site.overrideAttrs (_: {
  passthru = {
    mapsSrc = maps;
    inherit
      zigDeps
      mapmaker
      site
      data
      compressed
      ;
  };
})
