-- Narrow, lazy OSM data for two interactions only:
--   1. the four destination families generated by generate.py;
--   2. road/path direction facts used only by explicit highlighted-road snap.

node_keys = { "amenity", "healthcare", "shop" }
way_keys = { "amenity", "healthcare", "shop", "highway" }

local copied_identity_tags = {
  "name", "name:lt", "name:en", "int_name", "official_name", "brand", "operator",
  "addr:city", "addr:housename", "addr:housenumber", "addr:place", "addr:postcode", "addr:street"
}

local copied_destination_tags = {
  "amenity", "healthcare", "shop", "access", "foot", "wheelchair", "opening_hours",
  "cuisine", "phone", "contact:phone", "email", "contact:email", "website", "contact:website"
}

local copied_road_tags = {
  "highway", "access", "foot", "ref", "oneway", "destination", "destination:ref",
  "destination:street", "surface", "smoothness"
}

local lifecycle_keys = {
  "abandoned", "closed", "demolished", "destroyed", "disused", "proposed", "razed", "removed"
}

local former_highways = {
  abandoned = true, closed = true, demolished = true, destroyed = true,
  disused = true, proposed = true, razed = true, removed = true
}

-- Keep this in lockstep with the client-side roadDirectionHighways guard.
-- These are linear road/path values that can plausibly back a highlighted
-- access-network edge. Highway-tagged facilities and unknown future values
-- must not silently become direction cards.
local usable_highways = {
  motorway = true, motorway_link = true, trunk = true, trunk_link = true,
  primary = true, primary_link = true, secondary = true, secondary_link = true,
  tertiary = true, tertiary_link = true, unclassified = true, residential = true,
  living_street = true, service = true, pedestrian = true, track = true, road = true,
  path = true, footway = true, cycleway = true, bridleway = true, steps = true,
  corridor = true
}

-- Lifecycle booleans (disused=yes, abandoned=yes, …) apply to the whole
-- object. They do not hide a destination: the modal shows it, marked with the
-- resulting status, while generate.py keeps the same object out of routing.
-- razed/demolished/destroyed collapse to "removed"; the rest keep their word.
local lifecycle_status = {
  abandoned = "abandoned", closed = "closed", demolished = "removed",
  destroyed = "removed", disused = "disused", proposed = "proposed",
  razed = "removed", removed = "removed"
}

local function object_status()
  for _, key in ipairs(lifecycle_keys) do
    local value = string.lower(Find(key))
    if value == "yes" or value == "true" or value == "1" then
      return lifecycle_status[key]
    end
  end
  return "active"
end

-- A usable road/path must be a live edge: lifecycle-inactive linear geometry
-- can never back a routable access edge, so it is dropped rather than marked.
local function current_object()
  return object_status() == "active"
end

local function destination_service()
  local amenity = Find("amenity")
  local healthcare = Find("healthcare")
  local shop = Find("shop")
  if amenity == "cafe" or amenity == "restaurant" or shop == "coffee" then return "coffee" end
  if amenity == "hospital" or healthcare == "hospital" then return "hospital" end
  if shop == "supermarket" then return "supermarket" end
  if amenity == "fuel" then return "fuel" end
  return nil
end

local function destination_kind(service)
  if service ~= "coffee" then return service end
  local amenity = Find("amenity")
  if amenity == "restaurant" then return "restaurant" end
  if amenity == "cafe" then return "cafe" end
  return "coffee_shop"
end

local function copy(tags)
  for _, key in ipairs(tags) do
    local value = Find(key)
    if value ~= "" then Attribute(key, value) end
  end
end

local function common(osm_type)
  Attribute("osm_type", osm_type)
  Attribute("osm_id", Id())
  Attribute("status", object_status())
  copy(copied_identity_tags)
  MinZoom(15)
end

local function emit_destination(osm_type, layer, area)
  local service = destination_service()
  if not service then return false end
  Layer(layer, area)
  common(osm_type)
  Attribute("category", service == "hospital" and "healthcare" or service == "supermarket" and "retail" or "amenity")
  Attribute("kind", destination_kind(service))
  Attribute("search_service", service)
  copy(copied_destination_tags)
  return true
end

function node_function()
  emit_destination("node", "inspect_points", false)
end

function way_function()
  local osm_type = Find("type") == "multipolygon" and "relation" or "way"
  if IsClosed() and emit_destination(osm_type, "inspect_areas", true) then return end
  local highway = Find("highway")
  if not usable_highways[highway] or string.lower(Find("area")) == "yes" or
      former_highways[highway] or not current_object() then return end
  Layer("inspect_lines", false)
  common(osm_type)
  Attribute("category", "transport")
  Attribute("kind", highway)
  copy(copied_road_tags)
end
